name: exstudio
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_analytics: ^11.0.0
  firebase_crashlytics: ^4.0.0
  firebase_messaging: ^15.0.0
  provider: ^6.1.2
  go_router: 5.1.2
  dio_refresh_bot: ^2.1.2
  dio: ^4.0.6
  scope_function: ^1.0.2
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.4
  expandable: ^5.0.1
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  page_transition: ^2.1.0
  url_launcher: ^6.2.5
  timeago: ^3.6.1
  json_path: ^0.7.1
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.6
  intl: any
  bloc: ^8.1.3
  table_calendar: ^3.0.0
  flutter_phoenix: ^1.1.1
  bottom_sheet: ^4.0.4
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: any

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/bebasNeue.ttf
    - family: BebasNeueRegular
      fonts:
        - asset: assets/fonts/BebasNeueProRegular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
