// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuHngR6qkmzqoPnCg7C_EQlxHX2ijSdB0',
    appId: '1:805115852281:android:ca357cc95c6bf98b7ab928',
    messagingSenderId: '805115852281',
    projectId: 'studioback',
    storageBucket: 'studioback.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwD8y7R_dM3tm0tptl7XILvHZX7VpxyoY',
    appId: '1:805115852281:ios:3f69ac7dbcd553ad7ab928',
    messagingSenderId: '805115852281',
    projectId: 'studioback',
    storageBucket: 'studioback.appspot.com',
    iosBundleId: 'com.example.exstudio',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjy0A2EY6_m0TPAw058eSQxH2ZVY4i-mA',
    appId: '1:805115852281:web:e9a1dde2ba7183ad7ab928',
    messagingSenderId: '805115852281',
    projectId: 'studioback',
    authDomain: 'studioback.firebaseapp.com',
    storageBucket: 'studioback.appspot.com',
    measurementId: 'G-PEBVHCWV39',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwD8y7R_dM3tm0tptl7XILvHZX7VpxyoY',
    appId: '1:805115852281:ios:3f69ac7dbcd553ad7ab928',
    messagingSenderId: '805115852281',
    projectId: 'studioback',
    storageBucket: 'studioback.appspot.com',
    iosBundleId: 'com.example.exstudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjy0A2EY6_m0TPAw058eSQxH2ZVY4i-mA',
    appId: '1:805115852281:web:d9219b2eeea8e4b57ab928',
    messagingSenderId: '805115852281',
    projectId: 'studioback',
    authDomain: 'studioback.firebaseapp.com',
    storageBucket: 'studioback.appspot.com',
    measurementId: 'G-NKKEDB7TX5',
  );

}